Vagrant.configure("2") do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false
  config.vm.define "webserver" do |subconfig|
    subconfig.vm.box = "ubuntu/trusty64"
    subconfig.vm.hostname = "Web-Server"
    subconfig.vm.network "private_network", ip: "192.168.50.4"
    subconfig.vm.network "forwarded_port", guest: 80, host: 8080
    subconfig.vm.network "forwarded_port", guest: 443, host: 8443
  end
  config.vm.define "webclient1" do |subconfig|
    subconfig.vm.box = "ubuntu/trusty64"
    subconfig.vm.hostname = "Web-Client-1"
    subconfig.vm.network "private_network", ip: "192.168.50.5"
    subconfig.vm.network "forwarded_port", guest: 80, host: 8081
    subconfig.vm.network "forwarded_port", guest: 443, host: 8444
  end
  config.vm.define "webclient2" do |subconfig|
    subconfig.vm.box = "ubuntu/trusty64"
    subconfig.vm.hostname = "Web-Client-2"	
    subconfig.vm.network "private_network", ip: "192.168.50.6"
    subconfig.vm.network "forwarded_port", guest: 80, host: 8082
    subconfig.vm.network "forwarded_port", guest: 443, host: 8445
  end
end
